# Generated by Django 5.2.7 on 2025-12-28 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('registration_number', models.CharField(max_length=64, unique=True)),
                ('department', models.CharField(blank=True, max_length=128)),
                ('course', models.CharField(blank=True, max_length=128)),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('interest_type', models.CharField(choices=[('research', 'Research'), ('project', 'Project'), ('both', 'Both')], default='both', max_length=16)),
                ('preferred_roles', models.CharField(blank=True, max_length=255)),
                ('experience_level', models.CharField(blank=True, max_length=64)),
                ('profile_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
