# Generated by Django 5.2.7 on 2025-12-28 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='campus_oss_repos',
            field=models.TextField(blank=True, help_text="Student's open-source projects (one URL per line)"),
        ),
        migrations.AddField(
            model_name='profile',
            name='external_oss_contributions',
            field=models.TextField(blank=True, help_text='External repos contributed to (one URL per line)'),
        ),
    ]
