# Generated by Django 5.2.7 on 2026-01-04 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='ratee_id',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='rating',
            name='rater_id',
            field=models.IntegerField(db_index=True),
        ),
    ]
